# Generated by Django 3.0.5 on 2020-06-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_variations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guitarist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('band', models.CharField(max_length=100)),
                ('born', models.DateField(verbose_name='Born')),
            ],
        ),
        migrations.AlterField(
            model_name='variations',
            name='date_created',
            field=models.IntegerField(verbose_name='Date Created'),
        ),
    ]
